grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 5
    verbose: 2

model_selection:
  module_0:
    class: LinearRegression
    module: sklearn.linear_model
    params:
      fit_intercept: true
    search_param_grid:
      fit_intercept:
      - true
      - false

  module_1:
    class: DecisionTreeRegressor
    module: sklearn.tree
    params:
      min_samples_split: 3
      max_depth: 3
    search_param_grid:
       min_samples_split :
         - 3
         - 4
       max_depth :
         - 4
         - 5

  module_2:
    class: RandomForestRegressor
    module: sklearn.ensemble
    params:
      min_samples_leaf: 3
    search_param_grid:
      min_samples_leaf:
        - 5
        - 7
        - 10
      max_depth:
        - 5
        - 7
        - 12

  module_3:
      class: GradientBoostingRegressor
      module: sklearn.ensemble
      params:
        min_samples_leaf: 3
      search_param_grid:
        min_samples_leaf:
          - 5
          - 7
          - 10
        max_depth:
          - 1
          - 3
          - 5


